// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package io.wilderness.warp;

public interface C2SHeartbeatReqOrBuilder extends
        // @@protoc_insertion_point(interface_extends:warp.C2SHeartbeatReq)
        com.google.protobuf.MessageOrBuilder {
}
