// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package io.wilderness.warp;

/**
 * Protobuf type {@code warp.C2SMessageReq}
 */
public final class C2SMessageReq extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:warp.C2SMessageReq)
        C2SMessageReqOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use C2SMessageReq.newBuilder() to construct.
    private C2SMessageReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private C2SMessageReq() {
        targetId_ = "";
        msg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new C2SMessageReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private C2SMessageReq(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        java.lang.String s = input.readStringRequireUtf8();

                        targetId_ = s;
                        break;
                    }
                    case 18: {
                        java.lang.String s = input.readStringRequireUtf8();

                        msg_ = s;
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return io.wilderness.warp.Chat.internal_static_warp_C2SMessageReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return io.wilderness.warp.Chat.internal_static_warp_C2SMessageReq_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        io.wilderness.warp.C2SMessageReq.class, io.wilderness.warp.C2SMessageReq.Builder.class);
    }

    public static final int TARGETID_FIELD_NUMBER = 1;
    private volatile java.lang.Object targetId_;

    /**
     * <code>string targetId = 1;</code>
     *
     * @return The targetId.
     */
    public java.lang.String getTargetId() {
        java.lang.Object ref = targetId_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            targetId_ = s;
            return s;
        }
    }

    /**
     * <code>string targetId = 1;</code>
     *
     * @return The bytes for targetId.
     */
    public com.google.protobuf.ByteString
    getTargetIdBytes() {
        java.lang.Object ref = targetId_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            targetId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object msg_;

    /**
     * <code>string msg = 2;</code>
     *
     * @return The msg.
     */
    public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            msg_ = s;
            return s;
        }
    }

    /**
     * <code>string msg = 2;</code>
     *
     * @return The bytes for msg.
     */
    public com.google.protobuf.ByteString
    getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            msg_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!getTargetIdBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, targetId_);
        }
        if (!getMsgBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
        }
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getTargetIdBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, targetId_);
        }
        if (!getMsgBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof io.wilderness.warp.C2SMessageReq)) {
            return super.equals(obj);
        }
        io.wilderness.warp.C2SMessageReq other = (io.wilderness.warp.C2SMessageReq) obj;

        if (!getTargetId()
                .equals(other.getTargetId())) return false;
        if (!getMsg()
                .equals(other.getMsg())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + TARGETID_FIELD_NUMBER;
        hash = (53 * hash) + getTargetId().hashCode();
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static io.wilderness.warp.C2SMessageReq parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static io.wilderness.warp.C2SMessageReq parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static io.wilderness.warp.C2SMessageReq parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static io.wilderness.warp.C2SMessageReq parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static io.wilderness.warp.C2SMessageReq parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static io.wilderness.warp.C2SMessageReq parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static io.wilderness.warp.C2SMessageReq parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static io.wilderness.warp.C2SMessageReq parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.wilderness.warp.C2SMessageReq parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static io.wilderness.warp.C2SMessageReq parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static io.wilderness.warp.C2SMessageReq parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static io.wilderness.warp.C2SMessageReq parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(io.wilderness.warp.C2SMessageReq prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code warp.C2SMessageReq}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:warp.C2SMessageReq)
            io.wilderness.warp.C2SMessageReqOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return io.wilderness.warp.Chat.internal_static_warp_C2SMessageReq_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return io.wilderness.warp.Chat.internal_static_warp_C2SMessageReq_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            io.wilderness.warp.C2SMessageReq.class, io.wilderness.warp.C2SMessageReq.Builder.class);
        }

        // Construct using io.wilderness.warp.C2SMessageReq.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            targetId_ = "";

            msg_ = "";

            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return io.wilderness.warp.Chat.internal_static_warp_C2SMessageReq_descriptor;
        }

        @java.lang.Override
        public io.wilderness.warp.C2SMessageReq getDefaultInstanceForType() {
            return io.wilderness.warp.C2SMessageReq.getDefaultInstance();
        }

        @java.lang.Override
        public io.wilderness.warp.C2SMessageReq build() {
            io.wilderness.warp.C2SMessageReq result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public io.wilderness.warp.C2SMessageReq buildPartial() {
            io.wilderness.warp.C2SMessageReq result = new io.wilderness.warp.C2SMessageReq(this);
            result.targetId_ = targetId_;
            result.msg_ = msg_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof io.wilderness.warp.C2SMessageReq) {
                return mergeFrom((io.wilderness.warp.C2SMessageReq) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(io.wilderness.warp.C2SMessageReq other) {
            if (other == io.wilderness.warp.C2SMessageReq.getDefaultInstance()) return this;
            if (!other.getTargetId().isEmpty()) {
                targetId_ = other.targetId_;
                onChanged();
            }
            if (!other.getMsg().isEmpty()) {
                msg_ = other.msg_;
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            io.wilderness.warp.C2SMessageReq parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (io.wilderness.warp.C2SMessageReq) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private java.lang.Object targetId_ = "";

        /**
         * <code>string targetId = 1;</code>
         *
         * @return The targetId.
         */
        public java.lang.String getTargetId() {
            java.lang.Object ref = targetId_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                targetId_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string targetId = 1;</code>
         *
         * @return The bytes for targetId.
         */
        public com.google.protobuf.ByteString
        getTargetIdBytes() {
            java.lang.Object ref = targetId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                targetId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string targetId = 1;</code>
         *
         * @param value The targetId to set.
         * @return This builder for chaining.
         */
        public Builder setTargetId(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            targetId_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string targetId = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearTargetId() {

            targetId_ = getDefaultInstance().getTargetId();
            onChanged();
            return this;
        }

        /**
         * <code>string targetId = 1;</code>
         *
         * @param value The bytes for targetId to set.
         * @return This builder for chaining.
         */
        public Builder setTargetIdBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            targetId_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object msg_ = "";

        /**
         * <code>string msg = 2;</code>
         *
         * @return The msg.
         */
        public java.lang.String getMsg() {
            java.lang.Object ref = msg_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                msg_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string msg = 2;</code>
         *
         * @return The bytes for msg.
         */
        public com.google.protobuf.ByteString
        getMsgBytes() {
            java.lang.Object ref = msg_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                msg_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string msg = 2;</code>
         *
         * @param value The msg to set.
         * @return This builder for chaining.
         */
        public Builder setMsg(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            msg_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string msg = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearMsg() {

            msg_ = getDefaultInstance().getMsg();
            onChanged();
            return this;
        }

        /**
         * <code>string msg = 2;</code>
         *
         * @param value The bytes for msg to set.
         * @return This builder for chaining.
         */
        public Builder setMsgBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            msg_ = value;
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:warp.C2SMessageReq)
    }

    // @@protoc_insertion_point(class_scope:warp.C2SMessageReq)
    private static final io.wilderness.warp.C2SMessageReq DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new io.wilderness.warp.C2SMessageReq();
    }

    public static io.wilderness.warp.C2SMessageReq getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<C2SMessageReq>
            PARSER = new com.google.protobuf.AbstractParser<C2SMessageReq>() {
        @java.lang.Override
        public C2SMessageReq parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new C2SMessageReq(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<C2SMessageReq> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<C2SMessageReq> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public io.wilderness.warp.C2SMessageReq getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

