// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package io.wilderness.warp;

public interface C2SMessageReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:warp.C2SMessageReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string targetId = 1;</code>
   * @return The targetId.
   */
  java.lang.String getTargetId();
  /**
   * <code>string targetId = 1;</code>
   * @return The bytes for targetId.
   */
  com.google.protobuf.ByteString
      getTargetIdBytes();

  /**
   * <code>string msg = 2;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 2;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
