// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package io.wilderness.warp;

/**
 * Protobuf type {@code warp.MessageChat}
 */
public  final class MessageChat extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:warp.MessageChat)
    MessageChatOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageChat.newBuilder() to construct.
  private MessageChat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageChat() {
    messageType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessageChat();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MessageChat(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            messageType_ = rawValue;
            break;
          }
          case 18: {
            io.wilderness.warp.C2SLoginReq.Builder subBuilder = null;
            if (messageBodyCase_ == 2) {
              subBuilder = ((io.wilderness.warp.C2SLoginReq) messageBody_).toBuilder();
            }
            messageBody_ =
                input.readMessage(io.wilderness.warp.C2SLoginReq.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.wilderness.warp.C2SLoginReq) messageBody_);
              messageBody_ = subBuilder.buildPartial();
            }
            messageBodyCase_ = 2;
            break;
          }
          case 26: {
            io.wilderness.warp.S2CLoginRes.Builder subBuilder = null;
            if (messageBodyCase_ == 3) {
              subBuilder = ((io.wilderness.warp.S2CLoginRes) messageBody_).toBuilder();
            }
            messageBody_ =
                input.readMessage(io.wilderness.warp.S2CLoginRes.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.wilderness.warp.S2CLoginRes) messageBody_);
              messageBody_ = subBuilder.buildPartial();
            }
            messageBodyCase_ = 3;
            break;
          }
          case 34: {
            io.wilderness.warp.C2SHeartbeatReq.Builder subBuilder = null;
            if (messageBodyCase_ == 4) {
              subBuilder = ((io.wilderness.warp.C2SHeartbeatReq) messageBody_).toBuilder();
            }
            messageBody_ =
                input.readMessage(io.wilderness.warp.C2SHeartbeatReq.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.wilderness.warp.C2SHeartbeatReq) messageBody_);
              messageBody_ = subBuilder.buildPartial();
            }
            messageBodyCase_ = 4;
            break;
          }
          case 42: {
            io.wilderness.warp.S2CHeartbeatRes.Builder subBuilder = null;
            if (messageBodyCase_ == 5) {
              subBuilder = ((io.wilderness.warp.S2CHeartbeatRes) messageBody_).toBuilder();
            }
            messageBody_ =
                input.readMessage(io.wilderness.warp.S2CHeartbeatRes.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.wilderness.warp.S2CHeartbeatRes) messageBody_);
              messageBody_ = subBuilder.buildPartial();
            }
            messageBodyCase_ = 5;
            break;
          }
          case 50: {
            io.wilderness.warp.C2SMessageReq.Builder subBuilder = null;
            if (messageBodyCase_ == 6) {
              subBuilder = ((io.wilderness.warp.C2SMessageReq) messageBody_).toBuilder();
            }
            messageBody_ =
                input.readMessage(io.wilderness.warp.C2SMessageReq.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.wilderness.warp.C2SMessageReq) messageBody_);
              messageBody_ = subBuilder.buildPartial();
            }
            messageBodyCase_ = 6;
            break;
          }
          case 58: {
            io.wilderness.warp.S2CMessageRes.Builder subBuilder = null;
            if (messageBodyCase_ == 7) {
              subBuilder = ((io.wilderness.warp.S2CMessageRes) messageBody_).toBuilder();
            }
            messageBody_ =
                input.readMessage(io.wilderness.warp.S2CMessageRes.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((io.wilderness.warp.S2CMessageRes) messageBody_);
              messageBody_ = subBuilder.buildPartial();
            }
            messageBodyCase_ = 7;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.wilderness.warp.Chat.internal_static_warp_MessageChat_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.wilderness.warp.Chat.internal_static_warp_MessageChat_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.wilderness.warp.MessageChat.class, io.wilderness.warp.MessageChat.Builder.class);
  }

  /**
   * Protobuf enum {@code warp.MessageChat.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>C2SLOGINREQ = 0;</code>
     */
    C2SLOGINREQ(0),
    /**
     * <code>S2CLOGINRES = 1;</code>
     */
    S2CLOGINRES(1),
    /**
     * <code>C2SHEARTBEATREQ = 2;</code>
     */
    C2SHEARTBEATREQ(2),
    /**
     * <code>S2CHEARTBEATRES = 3;</code>
     */
    S2CHEARTBEATRES(3),
    /**
     * <code>C2SMESSAGEREQ = 4;</code>
     */
    C2SMESSAGEREQ(4),
    /**
     * <code>S2CMESSAGERES = 5;</code>
     */
    S2CMESSAGERES(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>C2SLOGINREQ = 0;</code>
     */
    public static final int C2SLOGINREQ_VALUE = 0;
    /**
     * <code>S2CLOGINRES = 1;</code>
     */
    public static final int S2CLOGINRES_VALUE = 1;
    /**
     * <code>C2SHEARTBEATREQ = 2;</code>
     */
    public static final int C2SHEARTBEATREQ_VALUE = 2;
    /**
     * <code>S2CHEARTBEATRES = 3;</code>
     */
    public static final int S2CHEARTBEATRES_VALUE = 3;
    /**
     * <code>C2SMESSAGEREQ = 4;</code>
     */
    public static final int C2SMESSAGEREQ_VALUE = 4;
    /**
     * <code>S2CMESSAGERES = 5;</code>
     */
    public static final int S2CMESSAGERES_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return C2SLOGINREQ;
        case 1: return S2CLOGINRES;
        case 2: return C2SHEARTBEATREQ;
        case 3: return S2CHEARTBEATRES;
        case 4: return C2SMESSAGEREQ;
        case 5: return S2CMESSAGERES;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.wilderness.warp.MessageChat.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:warp.MessageChat.MessageType)
  }

  private int messageBodyCase_ = 0;
  private java.lang.Object messageBody_;
  public enum MessageBodyCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    LOGINREQ(2),
    LOGINRES(3),
    HEARTBEATREQ(4),
    HEARTBEATRES(5),
    MESSAGEREQ(6),
    MESSAGERES(7),
    MESSAGEBODY_NOT_SET(0);
    private final int value;
    private MessageBodyCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageBodyCase valueOf(int value) {
      return forNumber(value);
    }

    public static MessageBodyCase forNumber(int value) {
      switch (value) {
        case 2: return LOGINREQ;
        case 3: return LOGINRES;
        case 4: return HEARTBEATREQ;
        case 5: return HEARTBEATRES;
        case 6: return MESSAGEREQ;
        case 7: return MESSAGERES;
        case 0: return MESSAGEBODY_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MessageBodyCase
  getMessageBodyCase() {
    return MessageBodyCase.forNumber(
        messageBodyCase_);
  }

  public static final int MESSAGE_TYPE_FIELD_NUMBER = 1;
  private int messageType_;
  /**
   * <code>.warp.MessageChat.MessageType message_type = 1;</code>
   * @return The enum numeric value on the wire for messageType.
   */
  public int getMessageTypeValue() {
    return messageType_;
  }
  /**
   * <code>.warp.MessageChat.MessageType message_type = 1;</code>
   * @return The messageType.
   */
  public io.wilderness.warp.MessageChat.MessageType getMessageType() {
    @SuppressWarnings("deprecation")
    io.wilderness.warp.MessageChat.MessageType result = io.wilderness.warp.MessageChat.MessageType.valueOf(messageType_);
    return result == null ? io.wilderness.warp.MessageChat.MessageType.UNRECOGNIZED : result;
  }

  public static final int LOGINREQ_FIELD_NUMBER = 2;
  /**
   * <code>.warp.C2SLoginReq loginReq = 2;</code>
   * @return Whether the loginReq field is set.
   */
  public boolean hasLoginReq() {
    return messageBodyCase_ == 2;
  }
  /**
   * <code>.warp.C2SLoginReq loginReq = 2;</code>
   * @return The loginReq.
   */
  public io.wilderness.warp.C2SLoginReq getLoginReq() {
    if (messageBodyCase_ == 2) {
       return (io.wilderness.warp.C2SLoginReq) messageBody_;
    }
    return io.wilderness.warp.C2SLoginReq.getDefaultInstance();
  }
  /**
   * <code>.warp.C2SLoginReq loginReq = 2;</code>
   */
  public io.wilderness.warp.C2SLoginReqOrBuilder getLoginReqOrBuilder() {
    if (messageBodyCase_ == 2) {
       return (io.wilderness.warp.C2SLoginReq) messageBody_;
    }
    return io.wilderness.warp.C2SLoginReq.getDefaultInstance();
  }

  public static final int LOGINRES_FIELD_NUMBER = 3;
  /**
   * <code>.warp.S2CLoginRes loginRes = 3;</code>
   * @return Whether the loginRes field is set.
   */
  public boolean hasLoginRes() {
    return messageBodyCase_ == 3;
  }
  /**
   * <code>.warp.S2CLoginRes loginRes = 3;</code>
   * @return The loginRes.
   */
  public io.wilderness.warp.S2CLoginRes getLoginRes() {
    if (messageBodyCase_ == 3) {
       return (io.wilderness.warp.S2CLoginRes) messageBody_;
    }
    return io.wilderness.warp.S2CLoginRes.getDefaultInstance();
  }
  /**
   * <code>.warp.S2CLoginRes loginRes = 3;</code>
   */
  public io.wilderness.warp.S2CLoginResOrBuilder getLoginResOrBuilder() {
    if (messageBodyCase_ == 3) {
       return (io.wilderness.warp.S2CLoginRes) messageBody_;
    }
    return io.wilderness.warp.S2CLoginRes.getDefaultInstance();
  }

  public static final int HEARTBEATREQ_FIELD_NUMBER = 4;
  /**
   * <code>.warp.C2SHeartbeatReq heartbeatReq = 4;</code>
   * @return Whether the heartbeatReq field is set.
   */
  public boolean hasHeartbeatReq() {
    return messageBodyCase_ == 4;
  }
  /**
   * <code>.warp.C2SHeartbeatReq heartbeatReq = 4;</code>
   * @return The heartbeatReq.
   */
  public io.wilderness.warp.C2SHeartbeatReq getHeartbeatReq() {
    if (messageBodyCase_ == 4) {
       return (io.wilderness.warp.C2SHeartbeatReq) messageBody_;
    }
    return io.wilderness.warp.C2SHeartbeatReq.getDefaultInstance();
  }
  /**
   * <code>.warp.C2SHeartbeatReq heartbeatReq = 4;</code>
   */
  public io.wilderness.warp.C2SHeartbeatReqOrBuilder getHeartbeatReqOrBuilder() {
    if (messageBodyCase_ == 4) {
       return (io.wilderness.warp.C2SHeartbeatReq) messageBody_;
    }
    return io.wilderness.warp.C2SHeartbeatReq.getDefaultInstance();
  }

  public static final int HEARTBEATRES_FIELD_NUMBER = 5;
  /**
   * <code>.warp.S2CHeartbeatRes heartbeatRes = 5;</code>
   * @return Whether the heartbeatRes field is set.
   */
  public boolean hasHeartbeatRes() {
    return messageBodyCase_ == 5;
  }
  /**
   * <code>.warp.S2CHeartbeatRes heartbeatRes = 5;</code>
   * @return The heartbeatRes.
   */
  public io.wilderness.warp.S2CHeartbeatRes getHeartbeatRes() {
    if (messageBodyCase_ == 5) {
       return (io.wilderness.warp.S2CHeartbeatRes) messageBody_;
    }
    return io.wilderness.warp.S2CHeartbeatRes.getDefaultInstance();
  }
  /**
   * <code>.warp.S2CHeartbeatRes heartbeatRes = 5;</code>
   */
  public io.wilderness.warp.S2CHeartbeatResOrBuilder getHeartbeatResOrBuilder() {
    if (messageBodyCase_ == 5) {
       return (io.wilderness.warp.S2CHeartbeatRes) messageBody_;
    }
    return io.wilderness.warp.S2CHeartbeatRes.getDefaultInstance();
  }

  public static final int MESSAGEREQ_FIELD_NUMBER = 6;
  /**
   * <code>.warp.C2SMessageReq messageReq = 6;</code>
   * @return Whether the messageReq field is set.
   */
  public boolean hasMessageReq() {
    return messageBodyCase_ == 6;
  }
  /**
   * <code>.warp.C2SMessageReq messageReq = 6;</code>
   * @return The messageReq.
   */
  public io.wilderness.warp.C2SMessageReq getMessageReq() {
    if (messageBodyCase_ == 6) {
       return (io.wilderness.warp.C2SMessageReq) messageBody_;
    }
    return io.wilderness.warp.C2SMessageReq.getDefaultInstance();
  }
  /**
   * <code>.warp.C2SMessageReq messageReq = 6;</code>
   */
  public io.wilderness.warp.C2SMessageReqOrBuilder getMessageReqOrBuilder() {
    if (messageBodyCase_ == 6) {
       return (io.wilderness.warp.C2SMessageReq) messageBody_;
    }
    return io.wilderness.warp.C2SMessageReq.getDefaultInstance();
  }

  public static final int MESSAGERES_FIELD_NUMBER = 7;
  /**
   * <code>.warp.S2CMessageRes messageRes = 7;</code>
   * @return Whether the messageRes field is set.
   */
  public boolean hasMessageRes() {
    return messageBodyCase_ == 7;
  }
  /**
   * <code>.warp.S2CMessageRes messageRes = 7;</code>
   * @return The messageRes.
   */
  public io.wilderness.warp.S2CMessageRes getMessageRes() {
    if (messageBodyCase_ == 7) {
       return (io.wilderness.warp.S2CMessageRes) messageBody_;
    }
    return io.wilderness.warp.S2CMessageRes.getDefaultInstance();
  }
  /**
   * <code>.warp.S2CMessageRes messageRes = 7;</code>
   */
  public io.wilderness.warp.S2CMessageResOrBuilder getMessageResOrBuilder() {
    if (messageBodyCase_ == 7) {
       return (io.wilderness.warp.S2CMessageRes) messageBody_;
    }
    return io.wilderness.warp.S2CMessageRes.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageType_ != io.wilderness.warp.MessageChat.MessageType.C2SLOGINREQ.getNumber()) {
      output.writeEnum(1, messageType_);
    }
    if (messageBodyCase_ == 2) {
      output.writeMessage(2, (io.wilderness.warp.C2SLoginReq) messageBody_);
    }
    if (messageBodyCase_ == 3) {
      output.writeMessage(3, (io.wilderness.warp.S2CLoginRes) messageBody_);
    }
    if (messageBodyCase_ == 4) {
      output.writeMessage(4, (io.wilderness.warp.C2SHeartbeatReq) messageBody_);
    }
    if (messageBodyCase_ == 5) {
      output.writeMessage(5, (io.wilderness.warp.S2CHeartbeatRes) messageBody_);
    }
    if (messageBodyCase_ == 6) {
      output.writeMessage(6, (io.wilderness.warp.C2SMessageReq) messageBody_);
    }
    if (messageBodyCase_ == 7) {
      output.writeMessage(7, (io.wilderness.warp.S2CMessageRes) messageBody_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messageType_ != io.wilderness.warp.MessageChat.MessageType.C2SLOGINREQ.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, messageType_);
    }
    if (messageBodyCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (io.wilderness.warp.C2SLoginReq) messageBody_);
    }
    if (messageBodyCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (io.wilderness.warp.S2CLoginRes) messageBody_);
    }
    if (messageBodyCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (io.wilderness.warp.C2SHeartbeatReq) messageBody_);
    }
    if (messageBodyCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (io.wilderness.warp.S2CHeartbeatRes) messageBody_);
    }
    if (messageBodyCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (io.wilderness.warp.C2SMessageReq) messageBody_);
    }
    if (messageBodyCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (io.wilderness.warp.S2CMessageRes) messageBody_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.wilderness.warp.MessageChat)) {
      return super.equals(obj);
    }
    io.wilderness.warp.MessageChat other = (io.wilderness.warp.MessageChat) obj;

    if (messageType_ != other.messageType_) return false;
    if (!getMessageBodyCase().equals(other.getMessageBodyCase())) return false;
    switch (messageBodyCase_) {
      case 2:
        if (!getLoginReq()
            .equals(other.getLoginReq())) return false;
        break;
      case 3:
        if (!getLoginRes()
            .equals(other.getLoginRes())) return false;
        break;
      case 4:
        if (!getHeartbeatReq()
            .equals(other.getHeartbeatReq())) return false;
        break;
      case 5:
        if (!getHeartbeatRes()
            .equals(other.getHeartbeatRes())) return false;
        break;
      case 6:
        if (!getMessageReq()
            .equals(other.getMessageReq())) return false;
        break;
      case 7:
        if (!getMessageRes()
            .equals(other.getMessageRes())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + messageType_;
    switch (messageBodyCase_) {
      case 2:
        hash = (37 * hash) + LOGINREQ_FIELD_NUMBER;
        hash = (53 * hash) + getLoginReq().hashCode();
        break;
      case 3:
        hash = (37 * hash) + LOGINRES_FIELD_NUMBER;
        hash = (53 * hash) + getLoginRes().hashCode();
        break;
      case 4:
        hash = (37 * hash) + HEARTBEATREQ_FIELD_NUMBER;
        hash = (53 * hash) + getHeartbeatReq().hashCode();
        break;
      case 5:
        hash = (37 * hash) + HEARTBEATRES_FIELD_NUMBER;
        hash = (53 * hash) + getHeartbeatRes().hashCode();
        break;
      case 6:
        hash = (37 * hash) + MESSAGEREQ_FIELD_NUMBER;
        hash = (53 * hash) + getMessageReq().hashCode();
        break;
      case 7:
        hash = (37 * hash) + MESSAGERES_FIELD_NUMBER;
        hash = (53 * hash) + getMessageRes().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.wilderness.warp.MessageChat parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.wilderness.warp.MessageChat parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.wilderness.warp.MessageChat parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.wilderness.warp.MessageChat parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.wilderness.warp.MessageChat parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.wilderness.warp.MessageChat parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.wilderness.warp.MessageChat parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.wilderness.warp.MessageChat parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.wilderness.warp.MessageChat parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.wilderness.warp.MessageChat parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.wilderness.warp.MessageChat parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.wilderness.warp.MessageChat parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.wilderness.warp.MessageChat prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code warp.MessageChat}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:warp.MessageChat)
      io.wilderness.warp.MessageChatOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.wilderness.warp.Chat.internal_static_warp_MessageChat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.wilderness.warp.Chat.internal_static_warp_MessageChat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.wilderness.warp.MessageChat.class, io.wilderness.warp.MessageChat.Builder.class);
    }

    // Construct using io.wilderness.warp.MessageChat.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      messageType_ = 0;

      messageBodyCase_ = 0;
      messageBody_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.wilderness.warp.Chat.internal_static_warp_MessageChat_descriptor;
    }

    @java.lang.Override
    public io.wilderness.warp.MessageChat getDefaultInstanceForType() {
      return io.wilderness.warp.MessageChat.getDefaultInstance();
    }

    @java.lang.Override
    public io.wilderness.warp.MessageChat build() {
      io.wilderness.warp.MessageChat result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.wilderness.warp.MessageChat buildPartial() {
      io.wilderness.warp.MessageChat result = new io.wilderness.warp.MessageChat(this);
      result.messageType_ = messageType_;
      if (messageBodyCase_ == 2) {
        if (loginReqBuilder_ == null) {
          result.messageBody_ = messageBody_;
        } else {
          result.messageBody_ = loginReqBuilder_.build();
        }
      }
      if (messageBodyCase_ == 3) {
        if (loginResBuilder_ == null) {
          result.messageBody_ = messageBody_;
        } else {
          result.messageBody_ = loginResBuilder_.build();
        }
      }
      if (messageBodyCase_ == 4) {
        if (heartbeatReqBuilder_ == null) {
          result.messageBody_ = messageBody_;
        } else {
          result.messageBody_ = heartbeatReqBuilder_.build();
        }
      }
      if (messageBodyCase_ == 5) {
        if (heartbeatResBuilder_ == null) {
          result.messageBody_ = messageBody_;
        } else {
          result.messageBody_ = heartbeatResBuilder_.build();
        }
      }
      if (messageBodyCase_ == 6) {
        if (messageReqBuilder_ == null) {
          result.messageBody_ = messageBody_;
        } else {
          result.messageBody_ = messageReqBuilder_.build();
        }
      }
      if (messageBodyCase_ == 7) {
        if (messageResBuilder_ == null) {
          result.messageBody_ = messageBody_;
        } else {
          result.messageBody_ = messageResBuilder_.build();
        }
      }
      result.messageBodyCase_ = messageBodyCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.wilderness.warp.MessageChat) {
        return mergeFrom((io.wilderness.warp.MessageChat)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.wilderness.warp.MessageChat other) {
      if (other == io.wilderness.warp.MessageChat.getDefaultInstance()) return this;
      if (other.messageType_ != 0) {
        setMessageTypeValue(other.getMessageTypeValue());
      }
      switch (other.getMessageBodyCase()) {
        case LOGINREQ: {
          mergeLoginReq(other.getLoginReq());
          break;
        }
        case LOGINRES: {
          mergeLoginRes(other.getLoginRes());
          break;
        }
        case HEARTBEATREQ: {
          mergeHeartbeatReq(other.getHeartbeatReq());
          break;
        }
        case HEARTBEATRES: {
          mergeHeartbeatRes(other.getHeartbeatRes());
          break;
        }
        case MESSAGEREQ: {
          mergeMessageReq(other.getMessageReq());
          break;
        }
        case MESSAGERES: {
          mergeMessageRes(other.getMessageRes());
          break;
        }
        case MESSAGEBODY_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.wilderness.warp.MessageChat parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.wilderness.warp.MessageChat) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int messageBodyCase_ = 0;
    private java.lang.Object messageBody_;
    public MessageBodyCase
        getMessageBodyCase() {
      return MessageBodyCase.forNumber(
          messageBodyCase_);
    }

    public Builder clearMessageBody() {
      messageBodyCase_ = 0;
      messageBody_ = null;
      onChanged();
      return this;
    }


    private int messageType_ = 0;
    /**
     * <code>.warp.MessageChat.MessageType message_type = 1;</code>
     * @return The enum numeric value on the wire for messageType.
     */
    public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <code>.warp.MessageChat.MessageType message_type = 1;</code>
     * @param value The enum numeric value on the wire for messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageTypeValue(int value) {
      messageType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.warp.MessageChat.MessageType message_type = 1;</code>
     * @return The messageType.
     */
    public io.wilderness.warp.MessageChat.MessageType getMessageType() {
      @SuppressWarnings("deprecation")
      io.wilderness.warp.MessageChat.MessageType result = io.wilderness.warp.MessageChat.MessageType.valueOf(messageType_);
      return result == null ? io.wilderness.warp.MessageChat.MessageType.UNRECOGNIZED : result;
    }
    /**
     * <code>.warp.MessageChat.MessageType message_type = 1;</code>
     * @param value The messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageType(io.wilderness.warp.MessageChat.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      messageType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.warp.MessageChat.MessageType message_type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageType() {
      
      messageType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.wilderness.warp.C2SLoginReq, io.wilderness.warp.C2SLoginReq.Builder, io.wilderness.warp.C2SLoginReqOrBuilder> loginReqBuilder_;
    /**
     * <code>.warp.C2SLoginReq loginReq = 2;</code>
     * @return Whether the loginReq field is set.
     */
    public boolean hasLoginReq() {
      return messageBodyCase_ == 2;
    }
    /**
     * <code>.warp.C2SLoginReq loginReq = 2;</code>
     * @return The loginReq.
     */
    public io.wilderness.warp.C2SLoginReq getLoginReq() {
      if (loginReqBuilder_ == null) {
        if (messageBodyCase_ == 2) {
          return (io.wilderness.warp.C2SLoginReq) messageBody_;
        }
        return io.wilderness.warp.C2SLoginReq.getDefaultInstance();
      } else {
        if (messageBodyCase_ == 2) {
          return loginReqBuilder_.getMessage();
        }
        return io.wilderness.warp.C2SLoginReq.getDefaultInstance();
      }
    }
    /**
     * <code>.warp.C2SLoginReq loginReq = 2;</code>
     */
    public Builder setLoginReq(io.wilderness.warp.C2SLoginReq value) {
      if (loginReqBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageBody_ = value;
        onChanged();
      } else {
        loginReqBuilder_.setMessage(value);
      }
      messageBodyCase_ = 2;
      return this;
    }
    /**
     * <code>.warp.C2SLoginReq loginReq = 2;</code>
     */
    public Builder setLoginReq(
        io.wilderness.warp.C2SLoginReq.Builder builderForValue) {
      if (loginReqBuilder_ == null) {
        messageBody_ = builderForValue.build();
        onChanged();
      } else {
        loginReqBuilder_.setMessage(builderForValue.build());
      }
      messageBodyCase_ = 2;
      return this;
    }
    /**
     * <code>.warp.C2SLoginReq loginReq = 2;</code>
     */
    public Builder mergeLoginReq(io.wilderness.warp.C2SLoginReq value) {
      if (loginReqBuilder_ == null) {
        if (messageBodyCase_ == 2 &&
            messageBody_ != io.wilderness.warp.C2SLoginReq.getDefaultInstance()) {
          messageBody_ = io.wilderness.warp.C2SLoginReq.newBuilder((io.wilderness.warp.C2SLoginReq) messageBody_)
              .mergeFrom(value).buildPartial();
        } else {
          messageBody_ = value;
        }
        onChanged();
      } else {
        if (messageBodyCase_ == 2) {
          loginReqBuilder_.mergeFrom(value);
        }
        loginReqBuilder_.setMessage(value);
      }
      messageBodyCase_ = 2;
      return this;
    }
    /**
     * <code>.warp.C2SLoginReq loginReq = 2;</code>
     */
    public Builder clearLoginReq() {
      if (loginReqBuilder_ == null) {
        if (messageBodyCase_ == 2) {
          messageBodyCase_ = 0;
          messageBody_ = null;
          onChanged();
        }
      } else {
        if (messageBodyCase_ == 2) {
          messageBodyCase_ = 0;
          messageBody_ = null;
        }
        loginReqBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.warp.C2SLoginReq loginReq = 2;</code>
     */
    public io.wilderness.warp.C2SLoginReq.Builder getLoginReqBuilder() {
      return getLoginReqFieldBuilder().getBuilder();
    }
    /**
     * <code>.warp.C2SLoginReq loginReq = 2;</code>
     */
    public io.wilderness.warp.C2SLoginReqOrBuilder getLoginReqOrBuilder() {
      if ((messageBodyCase_ == 2) && (loginReqBuilder_ != null)) {
        return loginReqBuilder_.getMessageOrBuilder();
      } else {
        if (messageBodyCase_ == 2) {
          return (io.wilderness.warp.C2SLoginReq) messageBody_;
        }
        return io.wilderness.warp.C2SLoginReq.getDefaultInstance();
      }
    }
    /**
     * <code>.warp.C2SLoginReq loginReq = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.wilderness.warp.C2SLoginReq, io.wilderness.warp.C2SLoginReq.Builder, io.wilderness.warp.C2SLoginReqOrBuilder> 
        getLoginReqFieldBuilder() {
      if (loginReqBuilder_ == null) {
        if (!(messageBodyCase_ == 2)) {
          messageBody_ = io.wilderness.warp.C2SLoginReq.getDefaultInstance();
        }
        loginReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.wilderness.warp.C2SLoginReq, io.wilderness.warp.C2SLoginReq.Builder, io.wilderness.warp.C2SLoginReqOrBuilder>(
                (io.wilderness.warp.C2SLoginReq) messageBody_,
                getParentForChildren(),
                isClean());
        messageBody_ = null;
      }
      messageBodyCase_ = 2;
      onChanged();;
      return loginReqBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.wilderness.warp.S2CLoginRes, io.wilderness.warp.S2CLoginRes.Builder, io.wilderness.warp.S2CLoginResOrBuilder> loginResBuilder_;
    /**
     * <code>.warp.S2CLoginRes loginRes = 3;</code>
     * @return Whether the loginRes field is set.
     */
    public boolean hasLoginRes() {
      return messageBodyCase_ == 3;
    }
    /**
     * <code>.warp.S2CLoginRes loginRes = 3;</code>
     * @return The loginRes.
     */
    public io.wilderness.warp.S2CLoginRes getLoginRes() {
      if (loginResBuilder_ == null) {
        if (messageBodyCase_ == 3) {
          return (io.wilderness.warp.S2CLoginRes) messageBody_;
        }
        return io.wilderness.warp.S2CLoginRes.getDefaultInstance();
      } else {
        if (messageBodyCase_ == 3) {
          return loginResBuilder_.getMessage();
        }
        return io.wilderness.warp.S2CLoginRes.getDefaultInstance();
      }
    }
    /**
     * <code>.warp.S2CLoginRes loginRes = 3;</code>
     */
    public Builder setLoginRes(io.wilderness.warp.S2CLoginRes value) {
      if (loginResBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageBody_ = value;
        onChanged();
      } else {
        loginResBuilder_.setMessage(value);
      }
      messageBodyCase_ = 3;
      return this;
    }
    /**
     * <code>.warp.S2CLoginRes loginRes = 3;</code>
     */
    public Builder setLoginRes(
        io.wilderness.warp.S2CLoginRes.Builder builderForValue) {
      if (loginResBuilder_ == null) {
        messageBody_ = builderForValue.build();
        onChanged();
      } else {
        loginResBuilder_.setMessage(builderForValue.build());
      }
      messageBodyCase_ = 3;
      return this;
    }
    /**
     * <code>.warp.S2CLoginRes loginRes = 3;</code>
     */
    public Builder mergeLoginRes(io.wilderness.warp.S2CLoginRes value) {
      if (loginResBuilder_ == null) {
        if (messageBodyCase_ == 3 &&
            messageBody_ != io.wilderness.warp.S2CLoginRes.getDefaultInstance()) {
          messageBody_ = io.wilderness.warp.S2CLoginRes.newBuilder((io.wilderness.warp.S2CLoginRes) messageBody_)
              .mergeFrom(value).buildPartial();
        } else {
          messageBody_ = value;
        }
        onChanged();
      } else {
        if (messageBodyCase_ == 3) {
          loginResBuilder_.mergeFrom(value);
        }
        loginResBuilder_.setMessage(value);
      }
      messageBodyCase_ = 3;
      return this;
    }
    /**
     * <code>.warp.S2CLoginRes loginRes = 3;</code>
     */
    public Builder clearLoginRes() {
      if (loginResBuilder_ == null) {
        if (messageBodyCase_ == 3) {
          messageBodyCase_ = 0;
          messageBody_ = null;
          onChanged();
        }
      } else {
        if (messageBodyCase_ == 3) {
          messageBodyCase_ = 0;
          messageBody_ = null;
        }
        loginResBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.warp.S2CLoginRes loginRes = 3;</code>
     */
    public io.wilderness.warp.S2CLoginRes.Builder getLoginResBuilder() {
      return getLoginResFieldBuilder().getBuilder();
    }
    /**
     * <code>.warp.S2CLoginRes loginRes = 3;</code>
     */
    public io.wilderness.warp.S2CLoginResOrBuilder getLoginResOrBuilder() {
      if ((messageBodyCase_ == 3) && (loginResBuilder_ != null)) {
        return loginResBuilder_.getMessageOrBuilder();
      } else {
        if (messageBodyCase_ == 3) {
          return (io.wilderness.warp.S2CLoginRes) messageBody_;
        }
        return io.wilderness.warp.S2CLoginRes.getDefaultInstance();
      }
    }
    /**
     * <code>.warp.S2CLoginRes loginRes = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.wilderness.warp.S2CLoginRes, io.wilderness.warp.S2CLoginRes.Builder, io.wilderness.warp.S2CLoginResOrBuilder> 
        getLoginResFieldBuilder() {
      if (loginResBuilder_ == null) {
        if (!(messageBodyCase_ == 3)) {
          messageBody_ = io.wilderness.warp.S2CLoginRes.getDefaultInstance();
        }
        loginResBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.wilderness.warp.S2CLoginRes, io.wilderness.warp.S2CLoginRes.Builder, io.wilderness.warp.S2CLoginResOrBuilder>(
                (io.wilderness.warp.S2CLoginRes) messageBody_,
                getParentForChildren(),
                isClean());
        messageBody_ = null;
      }
      messageBodyCase_ = 3;
      onChanged();;
      return loginResBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.wilderness.warp.C2SHeartbeatReq, io.wilderness.warp.C2SHeartbeatReq.Builder, io.wilderness.warp.C2SHeartbeatReqOrBuilder> heartbeatReqBuilder_;
    /**
     * <code>.warp.C2SHeartbeatReq heartbeatReq = 4;</code>
     * @return Whether the heartbeatReq field is set.
     */
    public boolean hasHeartbeatReq() {
      return messageBodyCase_ == 4;
    }
    /**
     * <code>.warp.C2SHeartbeatReq heartbeatReq = 4;</code>
     * @return The heartbeatReq.
     */
    public io.wilderness.warp.C2SHeartbeatReq getHeartbeatReq() {
      if (heartbeatReqBuilder_ == null) {
        if (messageBodyCase_ == 4) {
          return (io.wilderness.warp.C2SHeartbeatReq) messageBody_;
        }
        return io.wilderness.warp.C2SHeartbeatReq.getDefaultInstance();
      } else {
        if (messageBodyCase_ == 4) {
          return heartbeatReqBuilder_.getMessage();
        }
        return io.wilderness.warp.C2SHeartbeatReq.getDefaultInstance();
      }
    }
    /**
     * <code>.warp.C2SHeartbeatReq heartbeatReq = 4;</code>
     */
    public Builder setHeartbeatReq(io.wilderness.warp.C2SHeartbeatReq value) {
      if (heartbeatReqBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageBody_ = value;
        onChanged();
      } else {
        heartbeatReqBuilder_.setMessage(value);
      }
      messageBodyCase_ = 4;
      return this;
    }
    /**
     * <code>.warp.C2SHeartbeatReq heartbeatReq = 4;</code>
     */
    public Builder setHeartbeatReq(
        io.wilderness.warp.C2SHeartbeatReq.Builder builderForValue) {
      if (heartbeatReqBuilder_ == null) {
        messageBody_ = builderForValue.build();
        onChanged();
      } else {
        heartbeatReqBuilder_.setMessage(builderForValue.build());
      }
      messageBodyCase_ = 4;
      return this;
    }
    /**
     * <code>.warp.C2SHeartbeatReq heartbeatReq = 4;</code>
     */
    public Builder mergeHeartbeatReq(io.wilderness.warp.C2SHeartbeatReq value) {
      if (heartbeatReqBuilder_ == null) {
        if (messageBodyCase_ == 4 &&
            messageBody_ != io.wilderness.warp.C2SHeartbeatReq.getDefaultInstance()) {
          messageBody_ = io.wilderness.warp.C2SHeartbeatReq.newBuilder((io.wilderness.warp.C2SHeartbeatReq) messageBody_)
              .mergeFrom(value).buildPartial();
        } else {
          messageBody_ = value;
        }
        onChanged();
      } else {
        if (messageBodyCase_ == 4) {
          heartbeatReqBuilder_.mergeFrom(value);
        }
        heartbeatReqBuilder_.setMessage(value);
      }
      messageBodyCase_ = 4;
      return this;
    }
    /**
     * <code>.warp.C2SHeartbeatReq heartbeatReq = 4;</code>
     */
    public Builder clearHeartbeatReq() {
      if (heartbeatReqBuilder_ == null) {
        if (messageBodyCase_ == 4) {
          messageBodyCase_ = 0;
          messageBody_ = null;
          onChanged();
        }
      } else {
        if (messageBodyCase_ == 4) {
          messageBodyCase_ = 0;
          messageBody_ = null;
        }
        heartbeatReqBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.warp.C2SHeartbeatReq heartbeatReq = 4;</code>
     */
    public io.wilderness.warp.C2SHeartbeatReq.Builder getHeartbeatReqBuilder() {
      return getHeartbeatReqFieldBuilder().getBuilder();
    }
    /**
     * <code>.warp.C2SHeartbeatReq heartbeatReq = 4;</code>
     */
    public io.wilderness.warp.C2SHeartbeatReqOrBuilder getHeartbeatReqOrBuilder() {
      if ((messageBodyCase_ == 4) && (heartbeatReqBuilder_ != null)) {
        return heartbeatReqBuilder_.getMessageOrBuilder();
      } else {
        if (messageBodyCase_ == 4) {
          return (io.wilderness.warp.C2SHeartbeatReq) messageBody_;
        }
        return io.wilderness.warp.C2SHeartbeatReq.getDefaultInstance();
      }
    }
    /**
     * <code>.warp.C2SHeartbeatReq heartbeatReq = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.wilderness.warp.C2SHeartbeatReq, io.wilderness.warp.C2SHeartbeatReq.Builder, io.wilderness.warp.C2SHeartbeatReqOrBuilder> 
        getHeartbeatReqFieldBuilder() {
      if (heartbeatReqBuilder_ == null) {
        if (!(messageBodyCase_ == 4)) {
          messageBody_ = io.wilderness.warp.C2SHeartbeatReq.getDefaultInstance();
        }
        heartbeatReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.wilderness.warp.C2SHeartbeatReq, io.wilderness.warp.C2SHeartbeatReq.Builder, io.wilderness.warp.C2SHeartbeatReqOrBuilder>(
                (io.wilderness.warp.C2SHeartbeatReq) messageBody_,
                getParentForChildren(),
                isClean());
        messageBody_ = null;
      }
      messageBodyCase_ = 4;
      onChanged();;
      return heartbeatReqBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.wilderness.warp.S2CHeartbeatRes, io.wilderness.warp.S2CHeartbeatRes.Builder, io.wilderness.warp.S2CHeartbeatResOrBuilder> heartbeatResBuilder_;
    /**
     * <code>.warp.S2CHeartbeatRes heartbeatRes = 5;</code>
     * @return Whether the heartbeatRes field is set.
     */
    public boolean hasHeartbeatRes() {
      return messageBodyCase_ == 5;
    }
    /**
     * <code>.warp.S2CHeartbeatRes heartbeatRes = 5;</code>
     * @return The heartbeatRes.
     */
    public io.wilderness.warp.S2CHeartbeatRes getHeartbeatRes() {
      if (heartbeatResBuilder_ == null) {
        if (messageBodyCase_ == 5) {
          return (io.wilderness.warp.S2CHeartbeatRes) messageBody_;
        }
        return io.wilderness.warp.S2CHeartbeatRes.getDefaultInstance();
      } else {
        if (messageBodyCase_ == 5) {
          return heartbeatResBuilder_.getMessage();
        }
        return io.wilderness.warp.S2CHeartbeatRes.getDefaultInstance();
      }
    }
    /**
     * <code>.warp.S2CHeartbeatRes heartbeatRes = 5;</code>
     */
    public Builder setHeartbeatRes(io.wilderness.warp.S2CHeartbeatRes value) {
      if (heartbeatResBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageBody_ = value;
        onChanged();
      } else {
        heartbeatResBuilder_.setMessage(value);
      }
      messageBodyCase_ = 5;
      return this;
    }
    /**
     * <code>.warp.S2CHeartbeatRes heartbeatRes = 5;</code>
     */
    public Builder setHeartbeatRes(
        io.wilderness.warp.S2CHeartbeatRes.Builder builderForValue) {
      if (heartbeatResBuilder_ == null) {
        messageBody_ = builderForValue.build();
        onChanged();
      } else {
        heartbeatResBuilder_.setMessage(builderForValue.build());
      }
      messageBodyCase_ = 5;
      return this;
    }
    /**
     * <code>.warp.S2CHeartbeatRes heartbeatRes = 5;</code>
     */
    public Builder mergeHeartbeatRes(io.wilderness.warp.S2CHeartbeatRes value) {
      if (heartbeatResBuilder_ == null) {
        if (messageBodyCase_ == 5 &&
            messageBody_ != io.wilderness.warp.S2CHeartbeatRes.getDefaultInstance()) {
          messageBody_ = io.wilderness.warp.S2CHeartbeatRes.newBuilder((io.wilderness.warp.S2CHeartbeatRes) messageBody_)
              .mergeFrom(value).buildPartial();
        } else {
          messageBody_ = value;
        }
        onChanged();
      } else {
        if (messageBodyCase_ == 5) {
          heartbeatResBuilder_.mergeFrom(value);
        }
        heartbeatResBuilder_.setMessage(value);
      }
      messageBodyCase_ = 5;
      return this;
    }
    /**
     * <code>.warp.S2CHeartbeatRes heartbeatRes = 5;</code>
     */
    public Builder clearHeartbeatRes() {
      if (heartbeatResBuilder_ == null) {
        if (messageBodyCase_ == 5) {
          messageBodyCase_ = 0;
          messageBody_ = null;
          onChanged();
        }
      } else {
        if (messageBodyCase_ == 5) {
          messageBodyCase_ = 0;
          messageBody_ = null;
        }
        heartbeatResBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.warp.S2CHeartbeatRes heartbeatRes = 5;</code>
     */
    public io.wilderness.warp.S2CHeartbeatRes.Builder getHeartbeatResBuilder() {
      return getHeartbeatResFieldBuilder().getBuilder();
    }
    /**
     * <code>.warp.S2CHeartbeatRes heartbeatRes = 5;</code>
     */
    public io.wilderness.warp.S2CHeartbeatResOrBuilder getHeartbeatResOrBuilder() {
      if ((messageBodyCase_ == 5) && (heartbeatResBuilder_ != null)) {
        return heartbeatResBuilder_.getMessageOrBuilder();
      } else {
        if (messageBodyCase_ == 5) {
          return (io.wilderness.warp.S2CHeartbeatRes) messageBody_;
        }
        return io.wilderness.warp.S2CHeartbeatRes.getDefaultInstance();
      }
    }
    /**
     * <code>.warp.S2CHeartbeatRes heartbeatRes = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.wilderness.warp.S2CHeartbeatRes, io.wilderness.warp.S2CHeartbeatRes.Builder, io.wilderness.warp.S2CHeartbeatResOrBuilder> 
        getHeartbeatResFieldBuilder() {
      if (heartbeatResBuilder_ == null) {
        if (!(messageBodyCase_ == 5)) {
          messageBody_ = io.wilderness.warp.S2CHeartbeatRes.getDefaultInstance();
        }
        heartbeatResBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.wilderness.warp.S2CHeartbeatRes, io.wilderness.warp.S2CHeartbeatRes.Builder, io.wilderness.warp.S2CHeartbeatResOrBuilder>(
                (io.wilderness.warp.S2CHeartbeatRes) messageBody_,
                getParentForChildren(),
                isClean());
        messageBody_ = null;
      }
      messageBodyCase_ = 5;
      onChanged();;
      return heartbeatResBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.wilderness.warp.C2SMessageReq, io.wilderness.warp.C2SMessageReq.Builder, io.wilderness.warp.C2SMessageReqOrBuilder> messageReqBuilder_;
    /**
     * <code>.warp.C2SMessageReq messageReq = 6;</code>
     * @return Whether the messageReq field is set.
     */
    public boolean hasMessageReq() {
      return messageBodyCase_ == 6;
    }
    /**
     * <code>.warp.C2SMessageReq messageReq = 6;</code>
     * @return The messageReq.
     */
    public io.wilderness.warp.C2SMessageReq getMessageReq() {
      if (messageReqBuilder_ == null) {
        if (messageBodyCase_ == 6) {
          return (io.wilderness.warp.C2SMessageReq) messageBody_;
        }
        return io.wilderness.warp.C2SMessageReq.getDefaultInstance();
      } else {
        if (messageBodyCase_ == 6) {
          return messageReqBuilder_.getMessage();
        }
        return io.wilderness.warp.C2SMessageReq.getDefaultInstance();
      }
    }
    /**
     * <code>.warp.C2SMessageReq messageReq = 6;</code>
     */
    public Builder setMessageReq(io.wilderness.warp.C2SMessageReq value) {
      if (messageReqBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageBody_ = value;
        onChanged();
      } else {
        messageReqBuilder_.setMessage(value);
      }
      messageBodyCase_ = 6;
      return this;
    }
    /**
     * <code>.warp.C2SMessageReq messageReq = 6;</code>
     */
    public Builder setMessageReq(
        io.wilderness.warp.C2SMessageReq.Builder builderForValue) {
      if (messageReqBuilder_ == null) {
        messageBody_ = builderForValue.build();
        onChanged();
      } else {
        messageReqBuilder_.setMessage(builderForValue.build());
      }
      messageBodyCase_ = 6;
      return this;
    }
    /**
     * <code>.warp.C2SMessageReq messageReq = 6;</code>
     */
    public Builder mergeMessageReq(io.wilderness.warp.C2SMessageReq value) {
      if (messageReqBuilder_ == null) {
        if (messageBodyCase_ == 6 &&
            messageBody_ != io.wilderness.warp.C2SMessageReq.getDefaultInstance()) {
          messageBody_ = io.wilderness.warp.C2SMessageReq.newBuilder((io.wilderness.warp.C2SMessageReq) messageBody_)
              .mergeFrom(value).buildPartial();
        } else {
          messageBody_ = value;
        }
        onChanged();
      } else {
        if (messageBodyCase_ == 6) {
          messageReqBuilder_.mergeFrom(value);
        }
        messageReqBuilder_.setMessage(value);
      }
      messageBodyCase_ = 6;
      return this;
    }
    /**
     * <code>.warp.C2SMessageReq messageReq = 6;</code>
     */
    public Builder clearMessageReq() {
      if (messageReqBuilder_ == null) {
        if (messageBodyCase_ == 6) {
          messageBodyCase_ = 0;
          messageBody_ = null;
          onChanged();
        }
      } else {
        if (messageBodyCase_ == 6) {
          messageBodyCase_ = 0;
          messageBody_ = null;
        }
        messageReqBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.warp.C2SMessageReq messageReq = 6;</code>
     */
    public io.wilderness.warp.C2SMessageReq.Builder getMessageReqBuilder() {
      return getMessageReqFieldBuilder().getBuilder();
    }
    /**
     * <code>.warp.C2SMessageReq messageReq = 6;</code>
     */
    public io.wilderness.warp.C2SMessageReqOrBuilder getMessageReqOrBuilder() {
      if ((messageBodyCase_ == 6) && (messageReqBuilder_ != null)) {
        return messageReqBuilder_.getMessageOrBuilder();
      } else {
        if (messageBodyCase_ == 6) {
          return (io.wilderness.warp.C2SMessageReq) messageBody_;
        }
        return io.wilderness.warp.C2SMessageReq.getDefaultInstance();
      }
    }
    /**
     * <code>.warp.C2SMessageReq messageReq = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.wilderness.warp.C2SMessageReq, io.wilderness.warp.C2SMessageReq.Builder, io.wilderness.warp.C2SMessageReqOrBuilder> 
        getMessageReqFieldBuilder() {
      if (messageReqBuilder_ == null) {
        if (!(messageBodyCase_ == 6)) {
          messageBody_ = io.wilderness.warp.C2SMessageReq.getDefaultInstance();
        }
        messageReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.wilderness.warp.C2SMessageReq, io.wilderness.warp.C2SMessageReq.Builder, io.wilderness.warp.C2SMessageReqOrBuilder>(
                (io.wilderness.warp.C2SMessageReq) messageBody_,
                getParentForChildren(),
                isClean());
        messageBody_ = null;
      }
      messageBodyCase_ = 6;
      onChanged();;
      return messageReqBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        io.wilderness.warp.S2CMessageRes, io.wilderness.warp.S2CMessageRes.Builder, io.wilderness.warp.S2CMessageResOrBuilder> messageResBuilder_;
    /**
     * <code>.warp.S2CMessageRes messageRes = 7;</code>
     * @return Whether the messageRes field is set.
     */
    public boolean hasMessageRes() {
      return messageBodyCase_ == 7;
    }
    /**
     * <code>.warp.S2CMessageRes messageRes = 7;</code>
     * @return The messageRes.
     */
    public io.wilderness.warp.S2CMessageRes getMessageRes() {
      if (messageResBuilder_ == null) {
        if (messageBodyCase_ == 7) {
          return (io.wilderness.warp.S2CMessageRes) messageBody_;
        }
        return io.wilderness.warp.S2CMessageRes.getDefaultInstance();
      } else {
        if (messageBodyCase_ == 7) {
          return messageResBuilder_.getMessage();
        }
        return io.wilderness.warp.S2CMessageRes.getDefaultInstance();
      }
    }
    /**
     * <code>.warp.S2CMessageRes messageRes = 7;</code>
     */
    public Builder setMessageRes(io.wilderness.warp.S2CMessageRes value) {
      if (messageResBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageBody_ = value;
        onChanged();
      } else {
        messageResBuilder_.setMessage(value);
      }
      messageBodyCase_ = 7;
      return this;
    }
    /**
     * <code>.warp.S2CMessageRes messageRes = 7;</code>
     */
    public Builder setMessageRes(
        io.wilderness.warp.S2CMessageRes.Builder builderForValue) {
      if (messageResBuilder_ == null) {
        messageBody_ = builderForValue.build();
        onChanged();
      } else {
        messageResBuilder_.setMessage(builderForValue.build());
      }
      messageBodyCase_ = 7;
      return this;
    }
    /**
     * <code>.warp.S2CMessageRes messageRes = 7;</code>
     */
    public Builder mergeMessageRes(io.wilderness.warp.S2CMessageRes value) {
      if (messageResBuilder_ == null) {
        if (messageBodyCase_ == 7 &&
            messageBody_ != io.wilderness.warp.S2CMessageRes.getDefaultInstance()) {
          messageBody_ = io.wilderness.warp.S2CMessageRes.newBuilder((io.wilderness.warp.S2CMessageRes) messageBody_)
              .mergeFrom(value).buildPartial();
        } else {
          messageBody_ = value;
        }
        onChanged();
      } else {
        if (messageBodyCase_ == 7) {
          messageResBuilder_.mergeFrom(value);
        }
        messageResBuilder_.setMessage(value);
      }
      messageBodyCase_ = 7;
      return this;
    }
    /**
     * <code>.warp.S2CMessageRes messageRes = 7;</code>
     */
    public Builder clearMessageRes() {
      if (messageResBuilder_ == null) {
        if (messageBodyCase_ == 7) {
          messageBodyCase_ = 0;
          messageBody_ = null;
          onChanged();
        }
      } else {
        if (messageBodyCase_ == 7) {
          messageBodyCase_ = 0;
          messageBody_ = null;
        }
        messageResBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.warp.S2CMessageRes messageRes = 7;</code>
     */
    public io.wilderness.warp.S2CMessageRes.Builder getMessageResBuilder() {
      return getMessageResFieldBuilder().getBuilder();
    }
    /**
     * <code>.warp.S2CMessageRes messageRes = 7;</code>
     */
    public io.wilderness.warp.S2CMessageResOrBuilder getMessageResOrBuilder() {
      if ((messageBodyCase_ == 7) && (messageResBuilder_ != null)) {
        return messageResBuilder_.getMessageOrBuilder();
      } else {
        if (messageBodyCase_ == 7) {
          return (io.wilderness.warp.S2CMessageRes) messageBody_;
        }
        return io.wilderness.warp.S2CMessageRes.getDefaultInstance();
      }
    }
    /**
     * <code>.warp.S2CMessageRes messageRes = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.wilderness.warp.S2CMessageRes, io.wilderness.warp.S2CMessageRes.Builder, io.wilderness.warp.S2CMessageResOrBuilder> 
        getMessageResFieldBuilder() {
      if (messageResBuilder_ == null) {
        if (!(messageBodyCase_ == 7)) {
          messageBody_ = io.wilderness.warp.S2CMessageRes.getDefaultInstance();
        }
        messageResBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.wilderness.warp.S2CMessageRes, io.wilderness.warp.S2CMessageRes.Builder, io.wilderness.warp.S2CMessageResOrBuilder>(
                (io.wilderness.warp.S2CMessageRes) messageBody_,
                getParentForChildren(),
                isClean());
        messageBody_ = null;
      }
      messageBodyCase_ = 7;
      onChanged();;
      return messageResBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:warp.MessageChat)
  }

  // @@protoc_insertion_point(class_scope:warp.MessageChat)
  private static final io.wilderness.warp.MessageChat DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.wilderness.warp.MessageChat();
  }

  public static io.wilderness.warp.MessageChat getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageChat>
      PARSER = new com.google.protobuf.AbstractParser<MessageChat>() {
    @java.lang.Override
    public MessageChat parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MessageChat(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MessageChat> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageChat> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.wilderness.warp.MessageChat getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

