// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package io.wilderness.warp;

public final class Chat {
    private Chat() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_warp_MessageChat_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_warp_MessageChat_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_warp_C2SLoginReq_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_warp_C2SLoginReq_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_warp_S2CLoginRes_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_warp_S2CLoginRes_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_warp_C2SHeartbeatReq_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_warp_C2SHeartbeatReq_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_warp_S2CHeartbeatRes_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_warp_S2CHeartbeatRes_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_warp_C2SMessageReq_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_warp_C2SMessageReq_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_warp_S2CMessageRes_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_warp_S2CMessageRes_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\nchat.proto\022\004warp\"\324\003\n\013MessageChat\0223\n\014me" +
                        "ssage_type\030\001 \001(\0162\035.warp.MessageChat.Mess" +
                        "ageType\022%\n\010loginReq\030\002 \001(\0132\021.warp.C2SLogi" +
                        "nReqH\000\022%\n\010loginRes\030\003 \001(\0132\021.warp.S2CLogin" +
                        "ResH\000\022-\n\014heartbeatReq\030\004 \001(\0132\025.warp.C2SHe" +
                        "artbeatReqH\000\022-\n\014heartbeatRes\030\005 \001(\0132\025.war" +
                        "p.S2CHeartbeatResH\000\022)\n\nmessageReq\030\006 \001(\0132" +
                        "\023.warp.C2SMessageReqH\000\022)\n\nmessageRes\030\007 \001" +
                        "(\0132\023.warp.S2CMessageResH\000\"\177\n\013MessageType" +
                        "\022\017\n\013C2SLOGINREQ\020\000\022\017\n\013S2CLOGINRES\020\001\022\023\n\017C2" +
                        "SHEARTBEATREQ\020\002\022\023\n\017S2CHEARTBEATRES\020\003\022\021\n\r" +
                        "C2SMESSAGEREQ\020\004\022\021\n\rS2CMESSAGERES\020\005B\r\n\013Me" +
                        "ssageBody\"-\n\013C2SLoginReq\022\014\n\004name\030\001 \001(\t\022\020" +
                        "\n\010password\030\002 \001(\t\"\035\n\013S2CLoginRes\022\016\n\006statu" +
                        "s\030\001 \001(\005\"\021\n\017C2SHeartbeatReq\"\021\n\017S2CHeartbe" +
                        "atRes\".\n\rC2SMessageReq\022\020\n\010targetId\030\001 \001(\t" +
                        "\022\013\n\003msg\030\002 \001(\t\".\n\rS2CMessageRes\022\020\n\010source" +
                        "Id\030\001 \001(\t\022\013\n\003msg\030\002 \001(\tB\034\n\022io.wilderness.w" +
                        "arpB\004ChatP\001b\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_warp_MessageChat_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_warp_MessageChat_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_warp_MessageChat_descriptor,
                new java.lang.String[]{"MessageType", "LoginReq", "LoginRes", "HeartbeatReq", "HeartbeatRes", "MessageReq", "MessageRes", "MessageBody",});
        internal_static_warp_C2SLoginReq_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_warp_C2SLoginReq_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_warp_C2SLoginReq_descriptor,
                new java.lang.String[]{"Name", "Password",});
        internal_static_warp_S2CLoginRes_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_warp_S2CLoginRes_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_warp_S2CLoginRes_descriptor,
                new java.lang.String[]{"Status",});
        internal_static_warp_C2SHeartbeatReq_descriptor =
                getDescriptor().getMessageTypes().get(3);
        internal_static_warp_C2SHeartbeatReq_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_warp_C2SHeartbeatReq_descriptor,
                new java.lang.String[]{});
        internal_static_warp_S2CHeartbeatRes_descriptor =
                getDescriptor().getMessageTypes().get(4);
        internal_static_warp_S2CHeartbeatRes_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_warp_S2CHeartbeatRes_descriptor,
                new java.lang.String[]{});
        internal_static_warp_C2SMessageReq_descriptor =
                getDescriptor().getMessageTypes().get(5);
        internal_static_warp_C2SMessageReq_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_warp_C2SMessageReq_descriptor,
                new java.lang.String[]{"TargetId", "Msg",});
        internal_static_warp_S2CMessageRes_descriptor =
                getDescriptor().getMessageTypes().get(6);
        internal_static_warp_S2CMessageRes_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_warp_S2CMessageRes_descriptor,
                new java.lang.String[]{"SourceId", "Msg",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
