// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package io.wilderness.warp;

public interface S2CMessageResOrBuilder extends
        // @@protoc_insertion_point(interface_extends:warp.S2CMessageRes)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string sourceId = 1;</code>
     *
     * @return The sourceId.
     */
    java.lang.String getSourceId();

    /**
     * <code>string sourceId = 1;</code>
     *
     * @return The bytes for sourceId.
     */
    com.google.protobuf.ByteString
    getSourceIdBytes();

    /**
     * <code>string msg = 2;</code>
     *
     * @return The msg.
     */
    java.lang.String getMsg();

    /**
     * <code>string msg = 2;</code>
     *
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString
    getMsgBytes();
}
