// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package io.wilderness.warp;

public interface MessageChatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:warp.MessageChat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.warp.MessageChat.MessageType message_type = 1;</code>
   * @return The enum numeric value on the wire for messageType.
   */
  int getMessageTypeValue();
  /**
   * <code>.warp.MessageChat.MessageType message_type = 1;</code>
   * @return The messageType.
   */
  io.wilderness.warp.MessageChat.MessageType getMessageType();

  /**
   * <code>.warp.C2SLoginReq loginReq = 2;</code>
   * @return Whether the loginReq field is set.
   */
  boolean hasLoginReq();
  /**
   * <code>.warp.C2SLoginReq loginReq = 2;</code>
   * @return The loginReq.
   */
  io.wilderness.warp.C2SLoginReq getLoginReq();
  /**
   * <code>.warp.C2SLoginReq loginReq = 2;</code>
   */
  io.wilderness.warp.C2SLoginReqOrBuilder getLoginReqOrBuilder();

  /**
   * <code>.warp.S2CLoginRes loginRes = 3;</code>
   * @return Whether the loginRes field is set.
   */
  boolean hasLoginRes();
  /**
   * <code>.warp.S2CLoginRes loginRes = 3;</code>
   * @return The loginRes.
   */
  io.wilderness.warp.S2CLoginRes getLoginRes();
  /**
   * <code>.warp.S2CLoginRes loginRes = 3;</code>
   */
  io.wilderness.warp.S2CLoginResOrBuilder getLoginResOrBuilder();

  /**
   * <code>.warp.C2SHeartbeatReq heartbeatReq = 4;</code>
   * @return Whether the heartbeatReq field is set.
   */
  boolean hasHeartbeatReq();
  /**
   * <code>.warp.C2SHeartbeatReq heartbeatReq = 4;</code>
   * @return The heartbeatReq.
   */
  io.wilderness.warp.C2SHeartbeatReq getHeartbeatReq();
  /**
   * <code>.warp.C2SHeartbeatReq heartbeatReq = 4;</code>
   */
  io.wilderness.warp.C2SHeartbeatReqOrBuilder getHeartbeatReqOrBuilder();

  /**
   * <code>.warp.S2CHeartbeatRes heartbeatRes = 5;</code>
   * @return Whether the heartbeatRes field is set.
   */
  boolean hasHeartbeatRes();
  /**
   * <code>.warp.S2CHeartbeatRes heartbeatRes = 5;</code>
   * @return The heartbeatRes.
   */
  io.wilderness.warp.S2CHeartbeatRes getHeartbeatRes();
  /**
   * <code>.warp.S2CHeartbeatRes heartbeatRes = 5;</code>
   */
  io.wilderness.warp.S2CHeartbeatResOrBuilder getHeartbeatResOrBuilder();

  /**
   * <code>.warp.C2SMessageReq messageReq = 6;</code>
   * @return Whether the messageReq field is set.
   */
  boolean hasMessageReq();
  /**
   * <code>.warp.C2SMessageReq messageReq = 6;</code>
   * @return The messageReq.
   */
  io.wilderness.warp.C2SMessageReq getMessageReq();
  /**
   * <code>.warp.C2SMessageReq messageReq = 6;</code>
   */
  io.wilderness.warp.C2SMessageReqOrBuilder getMessageReqOrBuilder();

  /**
   * <code>.warp.S2CMessageRes messageRes = 7;</code>
   * @return Whether the messageRes field is set.
   */
  boolean hasMessageRes();
  /**
   * <code>.warp.S2CMessageRes messageRes = 7;</code>
   * @return The messageRes.
   */
  io.wilderness.warp.S2CMessageRes getMessageRes();
  /**
   * <code>.warp.S2CMessageRes messageRes = 7;</code>
   */
  io.wilderness.warp.S2CMessageResOrBuilder getMessageResOrBuilder();

  public io.wilderness.warp.MessageChat.MessageBodyCase getMessageBodyCase();
}
