// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

package io.wilderness.warp;

public interface S2CHeartbeatResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:warp.S2CHeartbeatRes)
    com.google.protobuf.MessageOrBuilder {
}
